import { writeFile } from "fs/promises";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

import { SPELLBOOK, MILESTONES, CRIT_STATUS_BY_ELEMENT } from "../assets/data/spell_catalog.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const dest = resolve(__dirname, "../assets/data/spells.js");

const banner = `// Auto-generated by scripts/generateSpellbook.ts.\n` +
  `// Do not edit this file manually; update spell_catalog.ts and rerun the generator.\n\n`;

function serialize(obj: unknown) {
  return JSON.stringify(obj, null, 2);
}

async function run() {
  const body =
    `${banner}` +
    `export const SPELLBOOK = ${serialize(SPELLBOOK)};\n\n` +
    `export const MILESTONES = ${serialize(MILESTONES)};\n\n` +
    `export const STATUS_ON_CRIT = ${serialize(CRIT_STATUS_BY_ELEMENT)};\n`;

  await writeFile(dest, body, "utf-8");
  console.log(`Wrote ${dest}`);
}

run().catch(err => {
  console.error(err);
  process.exitCode = 1;
});

